[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "Reduino"
version = "0.0.3"
description = "Reduino transpiles Python scripts into efficient Arduino C++ and uploads automatically. A simple, intuitive way to control sensors, LEDs, and actuators without touching C++."
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [{ name = "Arnav Bajaj" , email= "arnavbajaj9@gmail.com"}]
keywords = ["arduino", "embedded", "transpiler", "robotics", "avr", "cpp"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Embedded Systems",
]

dependencies = [
  "pyserial",
  "pytest"
]

[project.optional-dependencies]
dev = ["pytest", "ruff", "mypy", "build", "twine"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["Reduino*"]

[tool.setuptools.package-data]
"Reduino" = ["templates/**", "assets/**"]

[tool.ruff]
line-length = 100

[project.urls]
Homepage = "https://github.com/Jackhammer9/Reduino"
Issues = "https://github.com/Jackhammer9/Reduino/issues"